# Generated by Django 5.2 on 2025-05-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPreference',
        ),
    ]
